# Infrastructure kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helm-release.yaml
  - helm-repository.yaml
  - namespace.yaml

# Replace base Namespace name and add all resources to this namespace
namespace: vault-secrets-operator-system

# Generate a re-usable name variable for other resources
configMapGenerator:
  - name: release-name
    literals:
      - releaseName="vault-secrets-operator"

    # This config resource is not added to the cluster
    options:
      annotations:
        config.kubernetes.io/local-config: "true"

# Source Chart Repo
  # url: https://github.com/hashicorp/vault-secrets-operator/tree/main/chart

# Teach kustomize how to update generated names
configurations:
  - kustomizeconfig.yaml

# Order matters!
components:

  # Update resources based on ConfigMap above
  - ../../../components/config-matcher
