# Infrastructure kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helm-release.yaml
  - helm-repository.yaml
  - operator-vault-auth.yaml
  - tailscale-oauth.yaml
  - namespace.yaml
  - tailscale-secret-service-account.yaml
  - cluster-admin.yaml

namespace: tailscale

configurations:
  - kustomizeconfig.yaml
