# This file is for teaching kustomize how to substitute names
---
nameReference:

- kind: HelmRepository
  fieldSpecs:

    # Update the HelmRelease spec.chartRef.name with the name of the corresponding OCIRepository
    - kind: HelmRelease
      path: spec/chart/spec/sourceRef/name

    # Update the operator hostname
    - kind: HelmRelease
      path: spec/values/operatorConfig/hostname
