# Kustomization for all Apps
#
# - deploy workloads by uncommenting resources below
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  config.fluxcd.io/workload-type: app

resources:
  - ./infrastructure-documentation
